service: serverless-http-dev
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  profile: neolife

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
